### ISSUE TITLE
CSS Libraries

### ISSUE THREAD

**Issue by sskhandek** [IllinoisWCS/IllinoisWCS.github.io#77]
Current: Bootstrap

**Comment by elchao96** [comment]
If we want something that has a lot of boilerplate out there (like standard colors and stuff), Material Design Lite is something we can look into. https://getmdl.io/index.html

BUT if your goal is to get AWAY from standardized looks (like bootstrap) and you're simply wanting a framework to aid with mobile responsiveness, then Skeleton might be the way to go. http://getskeleton.com/ - The main thing about Skeleton because it provides a grid and heading sizes, but it's not going to provide anything more (unlike Bootstrap's jumbotron, weird carousels, and yadayada).
