### ISSUE TITLE
UI Brainstorming for new Site

### ISSUE THREAD

**Issue by elchao96** [IllinoisWCS/IllinoisWCS.github.io#78]
Wasn't able to attend the brainstorming, any notes or drawings?

**Comment by sskhandek** [comment]
@elchao96 The main goal is meet to major milestones as far as restructuring the site so that it is composed of subpages instead of a giant scrolling page. We're going to start by reaching the first milestone of making these subpages and then after that, we go onto the enhancing the individual pages' designs. Then we convert the project to React :)

**Comment by elchao96** [comment]
Design inspo - http://pin.it/REPAJWV

**Comment by elchao96** [comment]
Interesting observation - Stanford and Penn both use the scrolling format that we use (both use Bootstrap + jQuery, which is what we use!). 
- [Stanford](https://web.stanford.edu/group/wics/)
- [Penn](http://wics.cis.upenn.edu/)

Brown's [site](http://cs.brown.edu/people/orgs/wics/index.html), although pretty minimalistic, is probably what we're kind of going for. 

Harvard's [site](http://www.harvardwics.com/) is made with Squarespace. But they have a sub-page model that we can look at.
