### ISSUE TITLE
Pull events from the Facebook Page instead of Google Calendar

### ISSUE THREAD

**Issue by sskhandek** [IllinoisWCS/IllinoisWCS.github.io#91]

**Comment by elchao96** [comment]
Currently, the issue with this is the fact that 
A) We manually update a Google Calendar.
2) The only 1:1 mapping guarantee (assuming no events are changed and that all events that go on the gCal are final) is the gCal to RSO gCal. 
C) We manually create Facebook Events.

BUT now, Facebook allows for events to be exported to a calendar for a given user (not sure for a FB page or if we can do granular events such that only export events that are for a certain group, etc. etc.). Perhaps, if we unified the two sources, we can make this happen. 

AKA tldr, can we have a script (or something running) such that whenever an officer updates the gCal (aka pull from officer gCal to regular gCal), the events get scribed to both the RSO gCal (which already happens) AND Facebook (which doesn't)... Then we'd be able to have some kind of get request just for Facebook that can be implemented onto the website. Just some thoughts because I don't like thinking about work after work.

**Comment by elchao96** [comment]
Downsides though are...maintenance. Like, the API probs will change and silently fail on both ends.

**Comment by sskhandek** [comment]
Low-pri, closing for now
